version: '3.4'

services:
  icat:
    container_name: icat
    hostname: icat
    restart: always
    image: rattel/icat:latest
    volumes:
      - data:/data
      - projects:/home/icat/projects
    ports:
      - "8888:8888"
    command: tail -F bla 
volumes:
  data:
  projects:
